[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "HBEPJPRWn75mkMjZDDVBuy8w7QTmSB4uhds8xXnUpo9w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
invoke = "yarn run ts-node -P ./tsconfig.json  scripts/invoke.ts"
